export const PACKET_SIZE_LENGTH = 4;
export const PACKET_ID_LENGTH = 1;
export const PACKET_HEADER_LENGTH = 5;

export const DUNGEON_STATUS = {
  MESSAGE: 0,
  ACTION: 1,
  TARGET: 2,
  SKILL_SELECTION: 3,
  PLAYER_ATTACK: 4,
  ENEMY_ATTACK: 5,
  MONSTER_DEAD: 6,
  GAME_OVER_WIN: 7,
  GAME_OVER_LOSE: 8,
  CONFIRM: 9,
  USE_ITEM: 10,
  FLEE_MESSAGE: 11,
};
