// src/constants/battle.js

export const DUNGEON_STATUS = {
  MESSAGE: 0,
  ACTION: 1,
  TARGET: 2,
  SKILL_SELECTION: 3,
  PLAYER_ATTACK: 4,
  ENEMY_ATTACK: 5,
  MONSTER_DEAD: 6,
  GAME_OVER_WIN: 7,
  GAME_OVER_LOSE: 8,
  CONFIRM: 9,
  USE_ITEM: 10,
  FLEE_MESSAGE: 11,
  REWARD: 12,
  SKILL_CHANGE: 13,
};

export const CONFIRM_TYPE = {
  DEFAULT: 0,
  FLEE: 1,
  STONE: 2,
  SKILLCHANGE: 3,
  GIVEUP: 4,
};

export const SKILL_RANK = {
  NORMAL: 100,
  RARE: 101,
  EPIC: 102,
  UNIQUE: 103,
  LEGENDARY: 104,
};

export const SKILL_ELEMENTAL = {
  ELECTRIC: 1000,
  STONE: 1001,
  PLANT: 1002,
  FIRE: 1003,
  WATER: 1004,
};

export const MAX_SKILL_REWARD = 3;
export const MAX_SKILL_COUNT = 4;
export const MAX_REWARD_BUTTON = 4;
